# Generated by Django 6.0.2 on 2026-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Rent', 'Rent'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], max_length=50),
        ),
    ]
