# Generated by Django 6.0.2 on 2026-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_category_alter_expense_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Rent', 'Rent'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Other', 'Other')], max_length=100),
        ),
    ]
