# Generated by Django 6.0.2 on 2026-04-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budget_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'managed': False},
        ),
    ]
