# Generated by Django 6.0.2 on 2026-04-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_budget_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='budget',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goal',
        ),
        migrations.AlterModelTable(
            name='income',
            table='income',
        ),
        migrations.AlterModelTable(
            name='saving',
            table='savings',
        ),
    ]
